name = "lefthook"
type = "cli"

[resolve]
git-url = "https://github.com/evilmartians/lefthook"

[platform.linux]
download-file = "lefthook_{version}_Linux_{arch}"

[platform.macos]
download-file = "lefthook_{version}_MacOS_{arch}"

[platform.windows]
download-file = "lefthook_{version}_Windows_{arch}.exe"

[install]
download-url = "https://github.com/evilmartians/lefthook/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/evilmartians/lefthook/releases/download/v{version}/lefthook_checksums.txt"

[install.arch]
x86 = "i386"
aarch64 = "arm64"
